export enum ProductOfferingType {
  TariffOrService = 1,
  AddOnData = 2,
  Setting = 3,
  Hardware = 4,
  Composite = 5,
  AddOnVoice = 6,
  AddOnSMS = 7,
  AddOnRoamingVoice = 8,
  AddOnInternationalVoice = 9,
  AddOnRoamingData = 10,
  AddOn = 11,
  AddOnDataShared = 12,
  TariffAndSharedData = 15,
  TariffAndData = 14,
  TariffAndDataAndVoice = 16,
  TariffAndDataAndVoiceAndSMS = 17,
  TariffAndDataAndSMS = 18,
  TariffAndVoice = 19,
  TariffAndVoiceAndSMS = 20,
  TariffAndSMS = 21,
  AddOnDataAndVoice = 22,
  AddOnDataAndVoiceAndSMS = 23,
  AddOnDataAndSMS = 24,
  AddOnVoiceAndSMS = 13
}
